---
- name: Deploy Apache Web Server with IP restrictions
  hosts: ubuntu
  become: true

  vars:
    apache_document_root: /var/www/html
    apache_server_name: mywebsite.local
    allowed_ips:
      - 192.168.1.10
      - 192.168.1.20
      - 192.168.1.30

  tasks:
    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Deploy Apache config template
      ansible.builtin.template:
        src: apache.conf.j2
        dest: /etc/apache2/sites-available/000-default.conf
        mode: '0644'
        owner: root
      notify: Restart Apache

    - name: Enable Apache site configuration
      ansible.builtin.command:
        cmd: a2ensite 000-default.conf
      notify: Restart Apache

    - name: Start and enable Apache
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true

  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: restarted
