---
- name: Deploy nginx with restrictions on IPs
  hosts: ubuntu
  become: true
  vars:
    nginx_document_root: /var/www/html
    nginx_server_name: mynginx.local
    allowed_ips:
      - 192.168.1.10
      - 192.168.1.20
      - 192.168.1.30
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
    
    - name: Deploy nginx config template
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
        mode: '0664'
        owner: root
      notify: Restart nginx
    
    - name: enable nginx site configuration
      ansible.builtin.file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart nginx
    
    - name: Start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted